# -*- coding: utf-8 -*-
"""Logic_Building_Task_1_Prany_Pilli.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZqzlSeLnMEOXmA-pz8ZNszsz9q1gB6u
"""

#Logic Building Task - 1 (FEB 2026)
#1. User Login Check
#Real-World Applications: Authentication Systems

#Given credentials
username = "admin"
password = "1234"
#Taking input from user
entered_username = input("Enter username: ")
entered_password = input("Enter password: ")
if entered_username == username and entered_password == password:
    print("Login Successful")
else:
    print("Invalid Credentials")

# 2. Pass / Fail Analyzer
#Real=World Application: Academic Evaluation Systems

marks = [45, 78, 90, 33, 60]
pass_count = 0
fail_count = 0
#Checking each student's marks
for mark in marks:
    if mark >= 50:
        pass_count += 1
    else:
        fail_count += 1
#Printing final result
print("Total Students:", len(marks))
print("Number of Students Passed:", pass_count)
print("Number of Students Failed:", fail_count)

# 3. Simple Data Cleaner
#Real-World Application: Data Preprocessing

names = [" Alice ", "bob", " CHARLIE "]
cleaned_names = []
#Removing spaces and converting to Lowercase
for name in names:
    cleaned_names.append(name.strip().lower())
print("Cleaned Names:", cleaned_names)

# 4. Message Length Analyzer
#Real-World Application: Text Filtering Systems

messages = ["Hi", "Welcome to the platform", "OK"]
#Printing Length of each message
for message in messages:
    print(message, "-> Length:", len(message))
    #Flagging messages longer than 10 characters
    if len(message) > 10:
        print("Long Message")

# 5. Error Message Detector
#Real-World Application: Log Monitoring Systems

logs = ["INFO", "ERROR", "WARNING", "ERROR"]
error_count = 0
#Counting number of "ERROR" entries
for log in logs:
    if log == "ERROR":
        error_count += 1
print("Total ERROR messages:", error_count)